services:
  ivy:
    container_name: ivy_filter
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - 8076:8000
    environment:
      - IVY_FILTER_PORT = 8000 # Only use if it 